### ISSUE TITLE
Fix CNJ date extraction

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#46]

**Comment by Bjwebb** [comment]
I've fixed the worst of the date issues.

There's still 7 or so that are obviously badly in the future, so it's probably worth doing something about those eventually. It might have to be a filter on future dates though, because for some of them the date itself is wrong - http://www.camdennewjournal.com/news/2013/jan/its-web-intrigue-rare-slug-eating-spiders-are-discovered-among-cemeterys-gothic-tombs

**Comment by robredpath** [comment]
We've decided to just remove anything that's in the future
